### ISSUE TITLE
服务器连接失败

### ISSUE THREAD

**Issue by SoYoungxSoWhat** [tiangalon/dy_danmaku_java#1]
服务器连接失败
java.net.ProtocolException: Expected HTTP 101 response but was '200 OK'
	at okhttp3.internal.ws.RealWebSocket.checkUpgradeSuccess$okhttp(RealWebSocket.kt:196)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:167)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)

**Comment by SoYoungxSoWhat** [comment]
看了下  [DouyinLiveWebFetcher](https://github.com/saermart/DouyinLiveWebFetcher) 也不好用了

**Comment by tiangalon** [comment]
现在必须要有正确的Signature才能连接，其实相关的js我已经抠出来放resources里面了，就是环境补不好算出来的没法用

**Comment by tiangalon** [comment]
已修复Signature签名，目前实测可用，已更新

**Comment by SoYoungxSoWhat** [comment]
牛逼 拜读拜读
