### ISSUE TITLE
怀疑JDK21导致的idea控制台中文乱码

### ISSUE THREAD

**Issue by SoYoungxSoWhat** [tiangalon/dy_danmaku_java#4]
java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.kt:55)
	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:68)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:96)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:247)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:181)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:138)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)

**Comment by tiangalon** [comment]
我这边可以正常使用，没有复现这个问题，这个错误应该是因为websocket断了，可能是网络问题，也有可能是因为你或者服务端主动断开了连接

**Comment by SoYoungxSoWhat** [comment]
搞定了，jdk20不知道啥原因会导致idea console 乱码，自作聪明System.setOut(new PrintStream(System.out, true, "UTF-8"))转了一下导致的。降级jdk17就好了。
